// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: internal/proto/logogger.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricsValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id    string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Delta *int64   `protobuf:"zigzag64,3,opt,name=delta,proto3,oneof" json:"delta,omitempty"`
	Value *float64 `protobuf:"fixed64,4,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Hash  string   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *MetricsValue) Reset() {
	*x = MetricsValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_logogger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsValue) ProtoMessage() {}

func (x *MetricsValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logogger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsValue.ProtoReflect.Descriptor instead.
func (*MetricsValue) Descriptor() ([]byte, []int) {
	return file_internal_proto_logogger_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetricsValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricsValue) GetDelta() int64 {
	if x != nil && x.Delta != nil {
		return *x.Delta
	}
	return 0
}

func (x *MetricsValue) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *MetricsValue) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type MetricsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics []*MetricsValue `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *MetricsList) Reset() {
	*x = MetricsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_logogger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsList) ProtoMessage() {}

func (x *MetricsList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logogger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsList.ProtoReflect.Descriptor instead.
func (*MetricsList) Descriptor() ([]byte, []int) {
	return file_internal_proto_logogger_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsList) GetMetrics() []*MetricsValue {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_logogger_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logogger_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_proto_logogger_proto_rawDescGZIP(), []int{2}
}

var File_internal_proto_logogger_proto protoreflect.FileDescriptor

var file_internal_proto_logogger_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6c, 0x6f, 0x67, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x6c, 0x6f, 0x67, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x22, 0x90, 0x01, 0x0a, 0x0c, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19,
	0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x12, 0x48, 0x00, 0x52,
	0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x64, 0x65, 0x6c,
	0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3f, 0x0a, 0x0b,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c,
	0x6f, 0x67, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xa8, 0x02, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x6f, 0x67,
	0x67, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0d, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x2e, 0x6c, 0x6f, 0x67, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x16, 0x2e, 0x6c,
	0x6f, 0x67, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x12, 0x0f, 0x2e, 0x6c, 0x6f, 0x67, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x6c, 0x6f, 0x67, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0b, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x2e, 0x6c, 0x6f, 0x67, 0x6f,
	0x67, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x1a, 0x16, 0x2e, 0x6c, 0x6f, 0x67, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3c, 0x0a, 0x0c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x6c, 0x6f, 0x67, 0x6f,
	0x67, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x6c, 0x6f, 0x67, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12,
	0x0f, 0x2e, 0x6c, 0x6f, 0x67, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x0f, 0x2e, 0x6c, 0x6f, 0x67, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x42, 0x10, 0x5a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_logogger_proto_rawDescOnce sync.Once
	file_internal_proto_logogger_proto_rawDescData = file_internal_proto_logogger_proto_rawDesc
)

func file_internal_proto_logogger_proto_rawDescGZIP() []byte {
	file_internal_proto_logogger_proto_rawDescOnce.Do(func() {
		file_internal_proto_logogger_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_logogger_proto_rawDescData)
	})
	return file_internal_proto_logogger_proto_rawDescData
}

var file_internal_proto_logogger_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_logogger_proto_goTypes = []interface{}{
	(*MetricsValue)(nil), // 0: logogger.MetricsValue
	(*MetricsList)(nil),  // 1: logogger.MetricsList
	(*Empty)(nil),        // 2: logogger.Empty
}
var file_internal_proto_logogger_proto_depIdxs = []int32{
	0, // 0: logogger.MetricsList.metrics:type_name -> logogger.MetricsValue
	0, // 1: logogger.Logogger.RetrieveValue:input_type -> logogger.MetricsValue
	2, // 2: logogger.Logogger.ListValues:input_type -> logogger.Empty
	0, // 3: logogger.Logogger.UpdateValue:input_type -> logogger.MetricsValue
	1, // 4: logogger.Logogger.UpdateValues:input_type -> logogger.MetricsList
	2, // 5: logogger.Logogger.Ping:input_type -> logogger.Empty
	0, // 6: logogger.Logogger.RetrieveValue:output_type -> logogger.MetricsValue
	1, // 7: logogger.Logogger.ListValues:output_type -> logogger.MetricsList
	0, // 8: logogger.Logogger.UpdateValue:output_type -> logogger.MetricsValue
	1, // 9: logogger.Logogger.UpdateValues:output_type -> logogger.MetricsList
	2, // 10: logogger.Logogger.Ping:output_type -> logogger.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_logogger_proto_init() }
func file_internal_proto_logogger_proto_init() {
	if File_internal_proto_logogger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_logogger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_logogger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_logogger_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_proto_logogger_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_logogger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_logogger_proto_goTypes,
		DependencyIndexes: file_internal_proto_logogger_proto_depIdxs,
		MessageInfos:      file_internal_proto_logogger_proto_msgTypes,
	}.Build()
	File_internal_proto_logogger_proto = out.File
	file_internal_proto_logogger_proto_rawDesc = nil
	file_internal_proto_logogger_proto_goTypes = nil
	file_internal_proto_logogger_proto_depIdxs = nil
}
