// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.10
// source: internal/proto/logogger.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogoggerClient is the client API for Logogger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogoggerClient interface {
	RetrieveValue(ctx context.Context, in *MetricsValue, opts ...grpc.CallOption) (*MetricsValue, error)
	ListValues(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (Logogger_ListValuesClient, error)
	UpdateValue(ctx context.Context, in *MetricsValue, opts ...grpc.CallOption) (*MetricsValue, error)
	UpdateValues(ctx context.Context, in *MetricsList, opts ...grpc.CallOption) (Logogger_UpdateValuesClient, error)
	Ping(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type logoggerClient struct {
	cc grpc.ClientConnInterface
}

func NewLogoggerClient(cc grpc.ClientConnInterface) LogoggerClient {
	return &logoggerClient{cc}
}

func (c *logoggerClient) RetrieveValue(ctx context.Context, in *MetricsValue, opts ...grpc.CallOption) (*MetricsValue, error) {
	out := new(MetricsValue)
	err := c.cc.Invoke(ctx, "/logogger.Logogger/RetrieveValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logoggerClient) ListValues(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (Logogger_ListValuesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Logogger_ServiceDesc.Streams[0], "/logogger.Logogger/ListValues", opts...)
	if err != nil {
		return nil, err
	}
	x := &logoggerListValuesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Logogger_ListValuesClient interface {
	Recv() (*MetricsValue, error)
	grpc.ClientStream
}

type logoggerListValuesClient struct {
	grpc.ClientStream
}

func (x *logoggerListValuesClient) Recv() (*MetricsValue, error) {
	m := new(MetricsValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *logoggerClient) UpdateValue(ctx context.Context, in *MetricsValue, opts ...grpc.CallOption) (*MetricsValue, error) {
	out := new(MetricsValue)
	err := c.cc.Invoke(ctx, "/logogger.Logogger/UpdateValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logoggerClient) UpdateValues(ctx context.Context, in *MetricsList, opts ...grpc.CallOption) (Logogger_UpdateValuesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Logogger_ServiceDesc.Streams[1], "/logogger.Logogger/UpdateValues", opts...)
	if err != nil {
		return nil, err
	}
	x := &logoggerUpdateValuesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Logogger_UpdateValuesClient interface {
	Recv() (*MetricsValue, error)
	grpc.ClientStream
}

type logoggerUpdateValuesClient struct {
	grpc.ClientStream
}

func (x *logoggerUpdateValuesClient) Recv() (*MetricsValue, error) {
	m := new(MetricsValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *logoggerClient) Ping(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/logogger.Logogger/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogoggerServer is the server API for Logogger service.
// All implementations must embed UnimplementedLogoggerServer
// for forward compatibility
type LogoggerServer interface {
	RetrieveValue(context.Context, *MetricsValue) (*MetricsValue, error)
	ListValues(*EmptyMessage, Logogger_ListValuesServer) error
	UpdateValue(context.Context, *MetricsValue) (*MetricsValue, error)
	UpdateValues(*MetricsList, Logogger_UpdateValuesServer) error
	Ping(context.Context, *EmptyMessage) (*EmptyMessage, error)
	mustEmbedUnimplementedLogoggerServer()
}

// UnimplementedLogoggerServer must be embedded to have forward compatible implementations.
type UnimplementedLogoggerServer struct {
}

func (UnimplementedLogoggerServer) RetrieveValue(context.Context, *MetricsValue) (*MetricsValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveValue not implemented")
}
func (UnimplementedLogoggerServer) ListValues(*EmptyMessage, Logogger_ListValuesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListValues not implemented")
}
func (UnimplementedLogoggerServer) UpdateValue(context.Context, *MetricsValue) (*MetricsValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateValue not implemented")
}
func (UnimplementedLogoggerServer) UpdateValues(*MetricsList, Logogger_UpdateValuesServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateValues not implemented")
}
func (UnimplementedLogoggerServer) Ping(context.Context, *EmptyMessage) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLogoggerServer) mustEmbedUnimplementedLogoggerServer() {}

// UnsafeLogoggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogoggerServer will
// result in compilation errors.
type UnsafeLogoggerServer interface {
	mustEmbedUnimplementedLogoggerServer()
}

func RegisterLogoggerServer(s grpc.ServiceRegistrar, srv LogoggerServer) {
	s.RegisterService(&Logogger_ServiceDesc, srv)
}

func _Logogger_RetrieveValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogoggerServer).RetrieveValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logogger.Logogger/RetrieveValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogoggerServer).RetrieveValue(ctx, req.(*MetricsValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logogger_ListValues_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogoggerServer).ListValues(m, &logoggerListValuesServer{stream})
}

type Logogger_ListValuesServer interface {
	Send(*MetricsValue) error
	grpc.ServerStream
}

type logoggerListValuesServer struct {
	grpc.ServerStream
}

func (x *logoggerListValuesServer) Send(m *MetricsValue) error {
	return x.ServerStream.SendMsg(m)
}

func _Logogger_UpdateValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogoggerServer).UpdateValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logogger.Logogger/UpdateValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogoggerServer).UpdateValue(ctx, req.(*MetricsValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logogger_UpdateValues_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MetricsList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogoggerServer).UpdateValues(m, &logoggerUpdateValuesServer{stream})
}

type Logogger_UpdateValuesServer interface {
	Send(*MetricsValue) error
	grpc.ServerStream
}

type logoggerUpdateValuesServer struct {
	grpc.ServerStream
}

func (x *logoggerUpdateValuesServer) Send(m *MetricsValue) error {
	return x.ServerStream.SendMsg(m)
}

func _Logogger_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogoggerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logogger.Logogger/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogoggerServer).Ping(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Logogger_ServiceDesc is the grpc.ServiceDesc for Logogger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Logogger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logogger.Logogger",
	HandlerType: (*LogoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveValue",
			Handler:    _Logogger_RetrieveValue_Handler,
		},
		{
			MethodName: "UpdateValue",
			Handler:    _Logogger_UpdateValue_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Logogger_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListValues",
			Handler:       _Logogger_ListValues_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateValues",
			Handler:       _Logogger_UpdateValues_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/logogger.proto",
}
